version: '3'
services:
  deboot:
    build: .
    privileged: true
    volumes:
      - "./scripts:/scripts"
      - "./dist:/dist"
    # command: ["/scripts/deboot.sh", "armel", "squeeze", "http://archive.debian.org/debian/"]
    # command: ["/scripts/deboot.sh", "armel", "wheezy", "http://archive.debian.org/debian/"]
    # command: ["/scripts/deboot.sh", "armel", "jessie", "http://ftp.debian.org/debian/"]
    # command: ["/scripts/deboot.sh", "armel", "stretch", "http://ftp.debian.org/debian/"]
    # command: ["/scripts/deboot.sh", "armel", "buster", "http://ftp.fr.debian.org/debian/"]
    command: ["/scripts/deboot.sh", "armel", "bullseye", "http://ftp.fr.debian.org/debian/"]
  uboot:
    build: .
    command: ["/scripts/build_uboot.sh"]
    volumes:
      - "./scripts:/scripts"
      - "./dist:/dist"
  tftp:
    image: pghalliday/tftp
    ports:
      - "192.168.1.23:69:69/udp"
    volumes:
      - "./scripts:/scripts"
      # - "./dist/boot:/srv/tftp"
      - "./dist:/var/tftpboot"
