version: '3'
services:
  deboot:
    build: .
    volumes:
      - "./scripts:/scripts"
      - "./dist:/dist"
    # command: ["./deboot.sh", "armel", "squeeze", "http://archive.debian.org/debian/"]
    # command: ["./deboot.sh", "armel", "wheezy", "http://archive.debian.org/debian/"]
    # command: ["./deboot.sh", "armel", "jessie", "http://ftp.debian.org/debian/"]
    # command: ["./deboot.sh", "armel", "stretch", "http://ftp.debian.org/debian/"]
    command: ["./deboot.sh", "armel", "buster", "http://ftp.fr.debian.org/debian/"]
  uboot:
    build:
      context: .
      dockerfile: Dockerfile-uboot
    command: ["/scripts/build_uboot.sh"]
    volumes:
      - "./scripts:/scripts"
      - "./dist/uboot:/dist"
      - "./u-boot:/uboot"
  tftp:
    image: pghalliday/tftp
    ports:
      - "192.168.1.23:69:69/udp"
    volumes:
      - "./scripts:/scripts"
      # - "./dist/boot:/srv/tftp"
      - "./dist/boot:/var/tftpboot"
