# This is a basic workflow to help you get started with Actions

name: CI

env:
  DEBIAN_VERSION: bullseye
  UBOOT_VERSION: v2022.10

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  debian:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: armel

    - name: Build docker image
      run: docker-compose build

    - name: Debootstrap Debian using docker
      run: |
        docker run --rm --privileged multiarch/qemu-user-static:register
        # modprobe binfmt_misc
        docker-compose run deboot

    - name: Upload ${{ env.DEBIAN_VERSION }}-armel.final.tar.gz
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.DEBIAN_VERSION }}-armel.final.tar.gz
        path: ./dist/${{ env.DEBIAN_VERSION }}-armel.final.tar.gz

    - name: Upload uImage
      uses: actions/upload-artifact@v3
      with:
        name: uImage
        path: ./dist/uImage

  # This workflow contains a single job called "build"
  uboot:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: armel

    - name: Build docker image
      run: docker-compose build

    - name: Build u-boot using docker
      run: |
        docker-compose run uboot

    - name: Upload u-boot.kwb
      uses: actions/upload-artifact@v3
      with:
        name: u-boot.kwb
        path: ./dist/u-boot.kwb
