# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build docker image
      run: docker-compose build

    # - name: Debootstrap Debian using docker
    #   run: |
    #     modprobe binfmt_misc
    #     docker-compose run deboot

    - name: Build u-boot using docker
      run: |
        docker-compose run uboot

    - name: Upload buster-armel.tar.gz
      uses: actions/upload-artifact@v2
      with:
        name: buster-armel.tar.gz
        path: ./dist/buster-armel.tar.gz

    - name: Upload buster-armel.final.tar.gz
      uses: actions/upload-artifact@v2
      with:
        name: buster-armel.final.tar.gz
        path: ./dist/buster-armel.final.tar.gz

    - name: Upload uImage
      uses: actions/upload-artifact@v2
      with:
        name: uImage
        path: ./dist/uImage

    - name: Upload u-boot.kwb
      uses: actions/upload-artifact@v2
      with:
        name: u-boot.kwb
        path: ./dist/u-boot.kwb
